document.getElementById("RESULT").onclick = function() {

    let C = parseFloat(document.getElementById("CBTN").value);
    let T = parseFloat(document.getElementById("TTN").value);
    let TN = parseFloat(document.getElementById("TRN").value);

    if (isNaN(C) || isNaN(T) || isNaN(TN)) {
        alert("Invalid input. Please enter valid numbers.");
    }

     let total = Math.floor((T - TN)/C * 100)
       document.getElementById("Total").value = total

       if(C >= '1'){
        if(total >= '-100' && total <= '-49'){
            document.getElementById("box1").style.backgroundColor = `yellow`;
            document.getElementById("box2").style.backgroundColor = `wheat`;
            document.getElementById("box3").style.backgroundColor = `wheat`;
            document.getElementById("box5").style.backgroundColor = `wheat`;
            document.getElementById("box4").style.backgroundColor = `wheat`;
            document.getElementById("box7").style.backgroundColor = `wheat`;
            document.getElementById("box6").style.backgroundColor = `wheat`;
            document.getElementById("box10").style.backgroundColor = `wheat`;
            document.getElementById("box31").style.backgroundColor = `wheat`;
            document.getElementById("box32").style.backgroundColor = `wheat`;
            document.getElementById("box41").style.backgroundColor = `wheat`;
            document.getElementById("box42").style.backgroundColor = `wheat`;
            document.getElementById("box43").style.backgroundColor = `wheat`;
            document.getElementById("box51").style.backgroundColor = `wheat`;
            document.getElementById("box52").style.backgroundColor = `wheat`;
            document.getElementById("box53").style.backgroundColor = `wheat`;
            document.getElementById("box54").style.backgroundColor = `wheat`;
            document.getElementById("box61").style.backgroundColor = `wheat`;
            document.getElementById("box62").style.backgroundColor = `wheat`;
            document.getElementById("box63").style.backgroundColor = `wheat`;
            document.getElementById("box64").style.backgroundColor = `wheat`;
            document.getElementById("box65").style.backgroundColor = `wheat`;
            document.getElementById("box71").style.backgroundColor = `wheat`;
            document.getElementById("box72").style.backgroundColor = `wheat`;
            document.getElementById("box73").style.backgroundColor = `wheat`;
            document.getElementById("box74").style.backgroundColor = `wheat`;
            document.getElementById("box75").style.backgroundColor = `wheat`;
            document.getElementById("box76").style.backgroundColor = `wheat`;
            document.getElementById("El").style.color = `yellow`;
            document.getElementById("Ex").style.color = `white`;
            document.getElementById("Up").style.color = `white`;
            document.getElementById("Dv").style.color = `white`;
            document.getElementById("Ad").style.color = `white`;
            document.getElementById("Ac").style.color = `white`;
            document.getElementById("At").style.color = `white`;
        }
      if(total >= '-50' && total <= '-26'){ 
            document.getElementById("box2").style.backgroundColor = `yellow`;
            document.getElementById("box10").style.backgroundColor = `yellow`;
            document.getElementById("box1").style.backgroundColor = `wheat`;
            document.getElementById("box5").style.backgroundColor = `wheat`;
            document.getElementById("box51").style.backgroundColor = `wheat`;
            document.getElementById("box52").style.backgroundColor = `wheat`;
            document.getElementById("box53").style.backgroundColor = `wheat`;
            document.getElementById("box54").style.backgroundColor = `wheat`;
            document.getElementById("box6").style.backgroundColor = `wheat`;
            document.getElementById("box61").style.backgroundColor = `wheat`;
            document.getElementById("box62").style.backgroundColor = `wheat`;
            document.getElementById("box63").style.backgroundColor = `wheat`;
            document.getElementById("box64").style.backgroundColor = `wheat`;
            document.getElementById("box65").style.backgroundColor = `wheat`;
            document.getElementById("box3").style.backgroundColor = `wheat`;
            document.getElementById("box31").style.backgroundColor = `wheat`;
            document.getElementById("box32").style.backgroundColor = `wheat`;
            document.getElementById("box4").style.backgroundColor = `wheat`;
            document.getElementById("box41").style.backgroundColor = `wheat`;
            document.getElementById("box42").style.backgroundColor = `wheat`;
            document.getElementById("box43").style.backgroundColor = `wheat`;
            document.getElementById("box71").style.backgroundColor = `wheat`;
            document.getElementById("box72").style.backgroundColor = `wheat`;
            document.getElementById("box73").style.backgroundColor = `wheat`;
            document.getElementById("box74").style.backgroundColor = `wheat`;
            document.getElementById("box75").style.backgroundColor = `wheat`;
            document.getElementById("box76").style.backgroundColor = `wheat`;
              document.getElementById("box76").style.backgroundColor = `wheat`;
              document.getElementById("box1").style.backgroundColor = `wheat`;
            document.getElementById("Dv").style.color = `yellow`;
            document.getElementById("Ex").style.color = `white`;
            document.getElementById("Up").style.color = `white`;
            document.getElementById("El").style.color = `white`;
            document.getElementById("Ad").style.color = `white`;
            document.getElementById("Ac").style.color = `white`;
            document.getElementById("At").style.color = `white`;
        }
        if(total >= '-25' && total <= '-1'){
            document.getElementById("box3").style.backgroundColor = `yellow`;
            document.getElementById("box31").style.backgroundColor = `yellow`;
            document.getElementById("box32").style.backgroundColor = `yellow`;
            document.getElementById("box2").style.backgroundColor = `wheat`;
            document.getElementById("box10").style.backgroundColor = `wheat`;
            document.getElementById("box1").style.backgroundColor = `wheat`;
            document.getElementById("box5").style.backgroundColor = `wheat`;
            document.getElementById("box51").style.backgroundColor = `wheat`;
            document.getElementById("box52").style.backgroundColor = `wheat`;
            document.getElementById("box53").style.backgroundColor = `wheat`;
            document.getElementById("box54").style.backgroundColor = `wheat`;
            document.getElementById("box6").style.backgroundColor = `wheat`;
            document.getElementById("box61").style.backgroundColor = `wheat`;
            document.getElementById("box62").style.backgroundColor = `wheat`;
            document.getElementById("box63").style.backgroundColor = `wheat`;
            document.getElementById("box64").style.backgroundColor = `wheat`;
            document.getElementById("box65").style.backgroundColor = `wheat`;
            document.getElementById("box4").style.backgroundColor = `wheat`;
            document.getElementById("box41").style.backgroundColor = `wheat`;
            document.getElementById("box42").style.backgroundColor = `wheat`;
            document.getElementById("box43").style.backgroundColor = `wheat`;
            document.getElementById("box2").style.backgroundColor = `wheat`;
            document.getElementById("box10").style.backgroundColor = `wheat`;
            document.getElementById("box7").style.backgroundColor = `wheat`;
            document.getElementById("box71").style.backgroundColor = `wheat`;
            document.getElementById("box72").style.backgroundColor = `wheat`;
            document.getElementById("box73").style.backgroundColor = `wheat`;
            document.getElementById("box74").style.backgroundColor = `wheat`;
            document.getElementById("box75").style.backgroundColor = `wheat`;
            document.getElementById("box76").style.backgroundColor = `wheat`;
            document.getElementById("box1").style.backgroundColor = `wheat`;
            document.getElementById("Ex").style.color = `yellow`;
            document.getElementById("Up").style.color = `white`;
            document.getElementById("El").style.color = `white`;
            document.getElementById("Ad").style.color = `white`;
            document.getElementById("Ac").style.color = `white`;
            document.getElementById("At").style.color = `white`;
            document.getElementById("Dv").style.color = `white`;
        }
        if(total >= '0' && total <='24'){

            document.getElementById("box4").style.backgroundColor = `yellow`;
            document.getElementById("box41").style.backgroundColor = `yellow`;
            document.getElementById("box42").style.backgroundColor = `yellow`;
            document.getElementById("box43").style.backgroundColor = `yellow`;
            document.getElementById("box5").style.backgroundColor = `wheat`;
            document.getElementById("box51").style.backgroundColor = `wheat`;
            document.getElementById("box52").style.backgroundColor = `wheat`;
            document.getElementById("box53").style.backgroundColor = `wheat`;
            document.getElementById("box54").style.backgroundColor = `wheat`;
            document.getElementById("box6").style.backgroundColor = `wheat`;
            document.getElementById("box61").style.backgroundColor = `wheat`;
            document.getElementById("box62").style.backgroundColor = `wheat`;
            document.getElementById("box63").style.backgroundColor = `wheat`;
            document.getElementById("box64").style.backgroundColor = `wheat`;
            document.getElementById("box65").style.backgroundColor = `wheat`;
            document.getElementById("box3").style.backgroundColor = `wheat`;
            document.getElementById("box31").style.backgroundColor = `wheat`;
            document.getElementById("box32").style.backgroundColor = `wheat`;
            document.getElementById("box2").style.backgroundColor = `wheat`;
            document.getElementById("box10").style.backgroundColor = `wheat`;
            document.getElementById("box71").style.backgroundColor = `wheat`;
            document.getElementById("box72").style.backgroundColor = `wheat`;
            document.getElementById("box73").style.backgroundColor = `wheat`;
            document.getElementById("box74").style.backgroundColor = `wheat`;
            document.getElementById("box75").style.backgroundColor = `wheat`;
            document.getElementById("box76").style.backgroundColor = `wheat`;
            document.getElementById("box7").style.backgroundColor = `wheat`;
            document.getElementById("box1").style.backgroundColor = `wheat`;
            document.getElementById("At").style.color = `yellow`;
            document.getElementById("Ex").style.color = `white`;
            document.getElementById("Up").style.color = `white`;
            document.getElementById("El").style.color = `white`;
            document.getElementById("Ad").style.color = `white`;
            document.getElementById("Ac").style.color = `white`;
            document.getElementById("Dv").style.color = `white`;
    
        }
        if(total >= '25' && total <='49'){

            document.getElementById("box5").style.backgroundColor = `yellow`;
            document.getElementById("box51").style.backgroundColor = `yellow`;
            document.getElementById("box52").style.backgroundColor = `yellow`;
            document.getElementById("box53").style.backgroundColor = `yellow`;
            document.getElementById("box54").style.backgroundColor = `yellow`;
            document.getElementById("box6").style.backgroundColor = `wheat`;
            document.getElementById("box61").style.backgroundColor = `wheat`;
            document.getElementById("box62").style.backgroundColor = `wheat`;
            document.getElementById("box63").style.backgroundColor = `wheat`;
            document.getElementById("box64").style.backgroundColor = `wheat`;
            document.getElementById("box65").style.backgroundColor = `wheat`;
            document.getElementById("box3").style.backgroundColor = `wheat`;
            document.getElementById("box31").style.backgroundColor = `wheat`;
            document.getElementById("box32").style.backgroundColor = `wheat`;
            document.getElementById("box4").style.backgroundColor = `wheat`;
            document.getElementById("box41").style.backgroundColor = `wheat`;
            document.getElementById("box42").style.backgroundColor = `wheat`;
            document.getElementById("box43").style.backgroundColor = `wheat`;
            document.getElementById("box2").style.backgroundColor = `wheat`;
            document.getElementById("box10").style.backgroundColor = `wheat`;
            document.getElementById("box71").style.backgroundColor = `wheat`;
            document.getElementById("box72").style.backgroundColor = `wheat`;
            document.getElementById("box73").style.backgroundColor = `wheat`;
            document.getElementById("box74").style.backgroundColor = `wheat`;
            document.getElementById("box75").style.backgroundColor = `wheat`;
            document.getElementById("box76").style.backgroundColor = `wheat`;
            document.getElementById("box7").style.backgroundColor = `wheat`;
            document.getElementById("box1").style.backgroundColor = `wheat`;
            document.getElementById("Ad").style.color = `yellow`;
            document.getElementById("Ex").style.color = `white`;
            document.getElementById("Up").style.color = `white`;
            document.getElementById("El").style.color = `white`;
            document.getElementById("Ac").style.color = `white`;
            document.getElementById("At").style.color = `white`;
            document.getElementById("Dv").style.color = `white`;
        }
        if(total >= '50' && total <= '99'){

            document.getElementById("box6").style.backgroundColor = `yellow`;
            document.getElementById("box61").style.backgroundColor = `yellow`;
            document.getElementById("box62").style.backgroundColor = `yellow`;
            document.getElementById("box63").style.backgroundColor = `yellow`;
            document.getElementById("box64").style.backgroundColor = `yellow`;
            document.getElementById("box65").style.backgroundColor = `yellow`;
            document.getElementById("box5").style.backgroundColor = `wheat`;
            document.getElementById("box51").style.backgroundColor = `wheat`;
            document.getElementById("box52").style.backgroundColor = `wheat`;
            document.getElementById("box53").style.backgroundColor = `wheat`;
            document.getElementById("box54").style.backgroundColor = `wheat`;
            document.getElementById("box3").style.backgroundColor = `wheat`;
            document.getElementById("box31").style.backgroundColor = `wheat`;
            document.getElementById("box32").style.backgroundColor = `wheat`;
            document.getElementById("box4").style.backgroundColor = `wheat`;
            document.getElementById("box41").style.backgroundColor = `wheat`;
            document.getElementById("box42").style.backgroundColor = `wheat`;
            document.getElementById("box43").style.backgroundColor = `wheat`;
            document.getElementById("box2").style.backgroundColor = `wheat`;
            document.getElementById("box10").style.backgroundColor = `wheat`;
            document.getElementById("box71").style.backgroundColor = `wheat`;
            document.getElementById("box72").style.backgroundColor = `wheat`;
            document.getElementById("box73").style.backgroundColor = `wheat`;
            document.getElementById("box74").style.backgroundColor = `wheat`;
            document.getElementById("box75").style.backgroundColor = `wheat`;
            document.getElementById("box76").style.backgroundColor = `wheat`;
            document.getElementById("box7").style.backgroundColor = `wheat`;
            document.getElementById("box1").style.backgroundColor = `wheat`;
            document.getElementById("Ac").style.color = `yellow`;
            document.getElementById("Ex").style.color = `white`;
            document.getElementById("Up").style.color = `white`;
            document.getElementById("El").style.color = `white`;
            document.getElementById("At").style.color = `white`;
            document.getElementById("Dv").style.color = `white`;
            document.getElementById("Ad").style.color = `white`;
        }
        if(total >= '100'){

            document.getElementById("box7").style.backgroundColor = `yellow`;
            document.getElementById("box71").style.backgroundColor = `yellow`;
            document.getElementById("box72").style.backgroundColor = `yellow`;
            document.getElementById("box73").style.backgroundColor = `yellow`;
            document.getElementById("box74").style.backgroundColor = `yellow`;
            document.getElementById("box75").style.backgroundColor = `yellow`;
            document.getElementById("box76").style.backgroundColor = `yellow`;
            document.getElementById("box5").style.backgroundColor = `wheat`;
            document.getElementById("box51").style.backgroundColor = `wheat`;
            document.getElementById("box52").style.backgroundColor = `wheat`;
            document.getElementById("box53").style.backgroundColor = `wheat`;
            document.getElementById("box54").style.backgroundColor = `wheat`;
            document.getElementById("box6").style.backgroundColor = `wheat`;
            document.getElementById("box61").style.backgroundColor = `wheat`;
            document.getElementById("box62").style.backgroundColor = `wheat`;
            document.getElementById("box63").style.backgroundColor = `wheat`;
            document.getElementById("box64").style.backgroundColor = `wheat`;
            document.getElementById("box65").style.backgroundColor = `wheat`;
            document.getElementById("box3").style.backgroundColor = `wheat`;
            document.getElementById("box31").style.backgroundColor = `wheat`;
            document.getElementById("box32").style.backgroundColor = `wheat`;
            document.getElementById("box4").style.backgroundColor = `wheat`;
            document.getElementById("box41").style.backgroundColor = `wheat`;
            document.getElementById("box42").style.backgroundColor = `wheat`;
            document.getElementById("box43").style.backgroundColor = `wheat`;
            document.getElementById("box2").style.backgroundColor = `wheat`;
            document.getElementById("box10").style.backgroundColor = `wheat`;
            document.getElementById("box1").style.backgroundColor = `wheat`;
            document.getElementById("Up").style.color = `yellow`;
            document.getElementById("Ex").style.color = `white`;
            document.getElementById("El").style.color = `white`;
            document.getElementById("At").style.color = `white`;
            document.getElementById("Ac").style.color = `white`;
            document.getElementById("At").style.color = `white`;
            document.getElementById("Dv").style.color = `white`;
            document.getElementById("Ad").style.color = `white`;
        }

       }
    }
document.getElementById("RESET").onclick = function() {
    document.getElementById("CBTN").value = "";
    document.getElementById("TTN").value = "";
    document.getElementById("TRN").value = "";
    document.getElementById("Total").value = ""; 
    document.getElementById("box1").style.backgroundColor = `wheat`;
    document.getElementById("box2").style.backgroundColor = `wheat`;
    document.getElementById("box3").style.backgroundColor = `wheat`;
    document.getElementById("box5").style.backgroundColor = `wheat`;
    document.getElementById("box4").style.backgroundColor = `wheat`;
    document.getElementById("box7").style.backgroundColor = `wheat`;
    document.getElementById("box6").style.backgroundColor = `wheat`;
    document.getElementById("box10").style.backgroundColor = `wheat`;
    document.getElementById("box31").style.backgroundColor = `wheat`;
    document.getElementById("box32").style.backgroundColor = `wheat`;
    document.getElementById("box41").style.backgroundColor = `wheat`;
    document.getElementById("box42").style.backgroundColor = `wheat`;
    document.getElementById("box43").style.backgroundColor = `wheat`;
    document.getElementById("box51").style.backgroundColor = `wheat`;
    document.getElementById("box52").style.backgroundColor = `wheat`;
    document.getElementById("box53").style.backgroundColor = `wheat`;
    document.getElementById("box54").style.backgroundColor = `wheat`;
    document.getElementById("box61").style.backgroundColor = `wheat`;
    document.getElementById("box62").style.backgroundColor = `wheat`;
    document.getElementById("box63").style.backgroundColor = `wheat`;
    document.getElementById("box64").style.backgroundColor = `wheat`;
    document.getElementById("box65").style.backgroundColor = `wheat`;
    document.getElementById("box71").style.backgroundColor = `wheat`;
    document.getElementById("box72").style.backgroundColor = `wheat`;
    document.getElementById("box73").style.backgroundColor = `wheat`;
    document.getElementById("box74").style.backgroundColor = `wheat`;
    document.getElementById("box75").style.backgroundColor = `wheat`;
    document.getElementById("box76").style.backgroundColor = `wheat`;
    document.getElementById("Up").style.color = `white`;
    document.getElementById("Ex").style.color = `white`;
    document.getElementById("El").style.color = `white`;
    document.getElementById("At").style.color = `white`;
    document.getElementById("Ac").style.color = `white`;
    document.getElementById("At").style.color = `white`;
    document.getElementById("Dv").style.color = `white`;
    document.getElementById("Ad").style.color = `white`;
}


